export { Homepage } from './Homepage'
export { ContentDetails } from './ContentDetails'
export { Movies } from './Movies'
export { TVShows } from './Shows'
export { Login } from './Login'
export { SearchResultsPage } from './SearchResults'
export { WatchList } from './WatchList'